use std::path::Path;
use crate::utils::fs;
use crate::utils::db;
use crate::config::Config;

/// Create a migration plan
pub async fn execute(config: &Config, from_version: Option<String>, to_version: Option<String>) -> Result<(), Box<dyn std::error::Error>> {
    if !config.is_dev() {
        println!("Plan command is disabled in production mode.");
        return Ok(());
    }

    let sql_base = config.sql_base();
    let from_version = from_version.unwrap_or_else(|| "latest".to_string());
    let to_version = to_version.unwrap_or_else(|| "next".to_string());

    // Resolve version aliases
    let resolved_from = if from_version == "latest" {
        fs::get_latest_version(sql_base)?
    } else {
        from_version
    };

    println!("Creating migration plan from version '{}' to '{}'", resolved_from, to_version);

    // Check if versions exist
    let from_dir = Path::new(sql_base).join(&resolved_from);
    let to_dir = Path::new(sql_base).join(&to_version);
    if !from_dir.exists() {
        return Err(format!("From version directory not found: {}", from_dir.display()).into());
    }
    if !to_dir.exists() {
        return Err(format!("To version directory not found: {}", to_dir.display()).into());
    }

    // Create temporary databases for each version and dump their schemas
    let from_dump = dump_version_schema(config, &resolved_from).await?;
    let to_dump = dump_version_schema(config, &to_version).await?;

    // Generate diff
    let diff = generate_diff(&from_dump, &to_dump)?;

    // Use LLM to create migration plan
    let migration_sql = generate_migration_plan_with_llm(config, &diff, &resolved_from, &to_version).await?;

    // Write migration plan to file
    let migration_file = format!("{}.sql", to_version);
    std::fs::write(&migration_file, &migration_sql)?;
    println!("Migration plan written to: {}", migration_file);

    Ok(())
}

/// Initialize a database at the given version and dump its schema
async fn dump_version_schema(config: &Config, version: &str) -> Result<String, Box<dyn std::error::Error>> {
    // Create a temporary database name
    let temp_db_name = format!("temp_plan_{}", version);

    // Clone config and set temp db name
    let mut temp_config = config.clone();
    temp_config.database.name = temp_db_name.clone();

    // Use the init command logic to initialize the temp database
    crate::commands::init::execute(&temp_config, Some(version.to_string())).await?;

    // Dump the schema
    let pool = db::get_db_pool(&temp_config).await?;
    let dump_sql = sqlx::query_scalar::<_, String>(
        "SELECT string_agg(pg_get_functiondef(oid), '; ') FROM pg_proc WHERE proname = 'pg_get_functiondef'"
    )
    .fetch_optional(&pool)
    .await?
    .unwrap_or_default();

    // TODO: Implement proper schema dump
    // For now, return a placeholder
    Ok(format!("-- Schema dump for version {}\n{}", version, dump_sql))
}

/// Generate diff between two schema dumps
fn generate_diff(from_dump: &str, to_dump: &str) -> Result<String, Box<dyn std::error::Error>> {
    // TODO: Implement proper diff
    Ok(format!("Diff:\nFrom:\n{}\nTo:\n{}", from_dump, to_dump))
}

/// Generate migration plan using LLM
async fn generate_migration_plan_with_llm(config: &Config, diff: &str, from_version: &str, to_version: &str) -> Result<String, Box<dyn std::error::Error>> {
    if !config.ai.enabled {
        return Err("AI is not enabled in configuration".into());
    }

    // TODO: Implement LLM integration
    Ok(format!("-- Migration from {} to {}\n-- Generated by LLM\n{}", from_version, to_version, diff))
}
