export enum DB_ERROR {
    NOT_FOUND = "DB_ERROR.NOT_FOUND",
    CORRUPTED = "DB_ERROR.CORRUPTED",
    CREATE_FAILED = "DB_ERROR.CREATE_FAILED",
    UPDATE_FAILED = "DB_ERROR.UPDATE_FAILED",
    DELETE_FAILED = "DB_ERROR.DELETE_FAILED",
    INVALID_VERSION = "DB_ERROR.INVALID_VERSION",
    INVALID_STATE = "DB_ERROR.INVALID_STATE",
    MIGRATION_PATH_NOT_FOUND = "DB_ERROR.MIGRATION_PATH_NOT_FOUND"
}
